# Generated by Django 5.1.7 on 2025-04-01 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project', 'Проект'), ('service', 'Услуга')], default='project', max_length=10, verbose_name='Тип')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_img/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Изображение проекта')),
                ('url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(['http', 'https'])], verbose_name='Ссылка на проект')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость работы')),
                ('deadline', models.DateField(verbose_name='Срок выполнения')),
            ],
            options={
                'verbose_name': 'Проект/Услуга',
                'verbose_name_plural': 'Проекты/Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название опции')),
                ('description', models.TextField(blank=True, verbose_name='Описание опции')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость опции')),
                ('deadline', models.DateField(verbose_name='Срок выполнения опции')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='projects.project', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Опция услуги',
                'verbose_name_plural': 'Опции услуг',
            },
        ),
    ]
