# Generated by Django 5.1.7 on 2025-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
        migrations.AddField(
            model_name='project',
            name='deadline_days',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Количество дней на выполнение работы', null=True, verbose_name='Срок выполнения (в днях)'),
        ),
    ]
