# Generated by Django 5.1.7 on 2025-04-06 11:15

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=apps.projects.models.MediaFile.get_upload_path),
        ),
    ]
