# Generated by Django 5.1.7 on 2025-04-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_mediafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
