# Generated by Django 5.1.7 on 2025-03-30 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_img/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), django.core.validators.MaxValueValidator(5242880, message='Размер не может превышать 50 МБ')], verbose_name='Фото профиля'),
        ),
    ]
