# Generated by Django 5.1.7 on 2025-04-04 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='orders', to='projects.serviceoption', verbose_name='Выбранные опции'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(limit_choices_to={'type': 'service'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='projects.project', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
